spring:
  application:
    name: GolfTournament

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

    hikari:
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public

country:
  countries:
    US: "united states of america"
    KR: "south korea"
    GB: "great britain"
    RU: "russia"
